In [3]:
import numpy as np
import matplotlib.pylab as plt

### 벡터/행렬의 덧셈과 뺄셈
- 같은 크기를 가진 두개의 벡터나 행렬은 덧셈과 뺄셈이 가능
- 같은 위치에 있는 원소끼리 연산 - 요소별 연산(element-wise)

In [4]:
x = np.array([10, 11, 12, 13, 14])
y = np.array([0, 1, 2, 3, 4])

In [5]:
x + y

array([10, 12, 14, 16, 18])

In [6]:
x - y

array([10, 10, 10, 10, 10])

In [8]:
A = np.array([[5, 6], [7, 8]]) + np.array([[10, 20], [30, 40]])

In [9]:
A - np.array([[1, 2], [3, 4]])

array([[14, 24],
       [34, 44]])

### 스칼라와 벡터/행렬의 곱셈
- 벡터 또는 행렬의 모든 원소에 스칼라값을 곱함

In [11]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

### 브로드캐스팅(broadcasting)
- 원래 덧셈과 뺄셈은 크기(차원)가 같은 두 벡터에 대해서만 가능
- 벡터와 스칼라의 경우에는 관례적으로 일벡터를 사용하여 스칼라를 벡터로 변환하여 연산을 허용
- 데이터 분석에서는 원래의 데이터 벡터 x가 아니라 그 데이터 벡터의 각 원소의 평균값을 뺀 평균제거(mean removed)벡터 혹은 0-평균(zero-mean)벡터를 사용하는 경우가 많다.

In [15]:
x = np.array([[1], [2], [3], [4]])

In [16]:
x + 10 * np.ones((4, 1))

array([[11.],
       [12.],
       [13.],
       [14.]])

### 선형조합(linear combination)
- 벡터/행렬에 스칼라값을 곱한 후 더하거나 뺀것
- 벡터나 행렬을 선형조합해도 크기는 변하지 않음

In [21]:
x = np.array([[1], [2], [3], [4]])
y = np.array([[4], [5], [6], [7]])

linear_combination = x * 10 + y * 10
linear_combination

array([[ 50],
       [ 70],
       [ 90],
       [110]])

### 벡터와 벡터의 곱셈
- 내적(inner product), 닷 프로덕트(dot product)
- 두 벡터의 차원(길이)가 같아야함
- 앞의 벡터가 행벡터이고 뒤의 벡터가 열벡터여야함
- 같은 위치에 있는 원소들을 요소별 곱셈처럼 곱한 다음, 그값들을 다시 모두 더하여 하나의 스칼라 값을 만듬

In [23]:
# numpy에서 내적은 dot() 또는 @(at이라고 읽음)으로 구함
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

In [24]:
x.T @ y, np.dot(x.T, y)

(array([[32]]), array([[32]]))

In [25]:
# numpy에서는 1차원 배열끼리도 내적 가능
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x @ y, np.dot(x, y)

(32, 32)